apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: v4m
  resources:
    requests:
      storage: 2Gi
